<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hannah Rogers' Portfolio</title>
    <link rel="stylesheet" href="styles/main.css">
</head>

<body>
    <header>
        <h1>Hannah Rogers</h1>
    </header>

    <nav>
        <ul class="navigation">
            <li><a class="ham" href="#">&#9776; Menu</a></li>
            <li><a href="index.html">Home</a></li>
            <li><a href="week1.html">Week 1</a></li>
            <li><a href="week2.html">Week 2</a></li>
            <li><a href="week3.html">Week 3</a></li>
            <li><a href="week4.html">Week 4</a></li>
            <li class="active"><a href="week5.html">Week 5</a></li>
        </ul>
    </nav>

    <main>
        <section>
            <h2>Week 5</h2>
            <h3>Reading Notes</h3>
        </section>

        <h3>Chapter 10: Testing and Debugging</h3>
        <p>Errors, exceptions, and warnings</p>
        <ul>
            <li>Errors are caused when soemthing goes wrong in a program via a system error, programmer error, or user error.</li>
            <li>Exceptions are errors that produce a return value that can be used by the program to deal with the error.</li>
            <li>Warnings can occur if there's an error that isn't enough to cause the program to crash. The program will continue running.</li>
        </ul>

        <p>Strict mode</p>
        <ul>
            <li>Produces more exceptions and warnings. Makes it easier to spot errors early on.</li>
            <li>Use by adding 'use strict' to the first line of a JS file. (create function)</li>
        </ul>

        <p>Debugging in the browser</p>
        <ul>
            <li>Use different ways to create breakpoints in your code so you can stop and see values etc.
                <ul>
                    <li>alert()</li>
                    <li>console.log()</li>
                    <li>console.trace()</li>
                </ul>
            </li>
            <li>Debugging tools are provided in most modern browsers. 
                <ul><li>Use 'debugger' keyword to make a breakpoint. Remember to remove.</li></ul>
            </li>
        </ul>

        <p>Error objects</p>
        <ul>
            <li>const error = new Error('Error message');</li>
            <li>Error objects for specific errors:
                <ul>
                    <li>EvalError</li>
                    <li>RangeError - a number is outside an allowable range of values.</li>
                    <li>ReferenceError - a reference is made to an item that doesn't exist.</li>
                    <li>SyntaxError - there's an error in the code's syntax.</li>
                    <li>TypeError - there wrong type of value is used.</li>
                    <li>URIError - there's a problem encoding or decoding the URI.</li>
                    <li>InternalError - error occurs in the JS engine</li>
                </ul>
            </li>
            <li>Error object properties that are generally safe to use:
                <ul>
                    <li>name - returns the name of the error constructor function.</li>
                    <li>message - returns a description of the error.</li>
                    <li>stack - returns a stack trace of the error.</li>
                </ul>
            </li>
        </ul>

        <p>Throwing exceptions</p>
        <ul>
            <li>Create your own exception with a 'throw' statement.</li>
            <li>You can throw an error object.</li>
        </ul>

        <p>Exception handling</p>
        <ul>
            <li>If we suspect a piece of code will result in an exception, we can wrap it in a try block. This will run the code inside the block as normal, but if an exception occurs it will pass the error object that is thrown onto a catch block.</li>
            <li>The code inside the catch block will only run if an exception is thrown inside the try block.</li>
            <li>A finally block can be added after a catch block. This will always be executed after the try or catch block, regardless of whether an exception occurred or not.</li>
        </ul>

        <p>Testing frameworks</p>
        <ul>
            <li>You can write your own tests or use a testing framework.</li>
            <li>Ex: Jest</li>
        </ul>
        
    </main>

    <footer></footer>
    
    <script src="scripts/main.js"></script>
</body>

</html>